name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.7' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install --ignore-installed coveralls
        pip install -I -e .[tests]
    - name: Start docker container
      run: |
        docker run -d -p 0.0.0.0:8945:5000 --name hepdata-converter-ws-tests hepdata/hepdata-converter-ws
        sleep 1
    - name: Run tests
      run: |
        coverage run -m unittest discover hepdata_converter_ws_client/testsuite 'test_*'
    - name: Run coveralls
      if: startsWith(matrix.python-version, '3')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls

  deploy:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Build PyPI package
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
